
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3308/lock_demo
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath*:com/luffyu/lock/db/**/*Mapper.xml
  type-aliases-package: com.luffyu.lock.db.**.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      #驼峰下划线转换
      table-underline: true
